// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCws2lKmzfwxs1PvKLggTgUcERUwaRWUKY',
    appId: '1:435426723896:web:ef199a1e6f8b7e2fea3ecd',
    messagingSenderId: '435426723896',
    projectId: 'inav-50f3e',
    authDomain: 'inav-50f3e.firebaseapp.com',
    storageBucket: 'inav-50f3e.firebasestorage.app',
    measurementId: 'G-R5G33XY2VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdoAcHL7PB6jl0icSwyimnOcw-Bvx6u1Q',
    appId: '1:435426723896:android:530f25e0b05f6c62ea3ecd',
    messagingSenderId: '435426723896',
    projectId: 'inav-50f3e',
    storageBucket: 'inav-50f3e.firebasestorage.app',
  );
}
